### PR TITLE
[Security] [Subplugin] check symlink before getting handle - @open sesame 05/08 15:22

### PR DESCRIPTION
**Pull request by jaeyun-jung**
1. Add code to check symlink before open file handle. 
2. Update code to handle error case of invalid params.

(fix one of security issues)
Signed-off-by: Jaeyun Jung <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by dongju-chae** [comment]
I'm not sure symbolic links are really problematic.
I think dlopen()-ing symbolic-linked libraries is not abnormal.
(e.g., XXX.so.6 --> XXX.so)

**Comment by jaeyun-jung** [comment]
@dongju-chae Security team reports this, please check the issue #1413.

**Comment by dongju-chae** [comment]
Okay, I found this information from the dlopen manual: "When loading shared objects, the application should open a specific version instead of relying on the version pointed to by a symbolic link".
Then, how about finding out a version-specified library name instead of just preventing a symbolic-linked one? (e.g., by using stat() function)

**Comment by jaeyun-jung** [comment]
@dongju-chae Added todo list about symbolic link file.

**Pull request merged**
