### PR TITLE
[Meson] update required meson version

### PR DESCRIPTION
**Pull request by jaeyun-jung**
Set min meson version 0.50 and cleanup the script.

Signed-off-by: Jaeyun Jung <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by wooksong** [comment]
Great! After merging this PR, I will update my PR as well

**Comment by jaeyun-jung** [comment]
I want to check the dependency of gtest with this PR.

**Comment by myungjoo** [comment]
You will be breaking all Ubuntu distros except for eoan. It may also break Yocto build as well. Check the available versions of them.

**Comment by jaeyun-jung** [comment]
meson version

eoan 0.51.2
disco 0.49.0 <<- failed
bionic 0.50.1
xenial 0.50.1

**Comment by wooksong** [comment]
> meson version
> 
> eoan 0.51.2
> disco 0.49.0 <<- failed
> bionic 0.50.1
> xenial 0.50.1

Do we have any other options for disco? 

FYI, meson in Yocto(openembeddedcore): 0.52

**Comment by myungjoo** [comment]
If we can add meson > 0.50 for all supported platforms by simply enabling just one more PPA recipe, then, it should be fine.

**Comment by wooksong** [comment]
@myungjoo @jaeyun-jung meson 0.50.1 for disco is ready.

**Pull request merged**
