### PR TITLE
V3, Tools: Added how to use tracers of GstShark

### PR DESCRIPTION
**Pull request by leemgs**
This commit is to append how to use the nine below tracers in GstShark.
All tracers were selected as a initial set of tracers based on RidgeRun's fine-tuning experience.
* InterLatency
* Processing time
* Frame rate
* Schedule time
* CPU usage
* Graphic
* Bitrate
* Queue Level
* Buffer

**Changes proposed in this PR:**
1. Added how to use GstShark tracers
2. Updated how to convert output data to a GNUplot data for analysis

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

---

### CODE REVIEW

**Comment by leemgs** [comment]
* After this PR:

image

**Comment by myungjoo** [comment]
#842

**Comment by leemgs** [comment]
**Changes proposed in this PR:**
* Version 2:
1. Added additional instruction manual for easy debugging
2. Fixed incorrect statements
3. Appended some commands to helpe GstShark newbie
4. Added screenshot of GstShark: graphic tracer

* Version 1:
1. Added how to use GstShark tracers
2. Updated how to convert output data to a GNUplot data for analysis

**Comment by leemgs** [comment]
* After version 2:
image

**Comment by leemgs** [comment]
**Changes proposed in this PR:**
* Version 3:
1. Added how to run gstshark-plot (Experimental)
2. Added how to create CTF (Common Trace Format) folder

* Version 2:
1. Added additional instruction manual for easy debugging
2. Fixed incorrect statements
3. Appended some commands to helpe GstShark newbie
4. Added screenshot of GstShark: graphic tracer

* Version 1:
1. Added how to use GstShark tracers
2. Updated how to convert output data to a GNUplot data for analysis

**Comment by leemgs** [comment]
* After V3: 
   * We could generate CTF files normally after V3. 
image

**Comment by leemgs** [comment]
The local test is done. This PR is ready to be merged.

**Pull request merged**
