### PR TITLE
[Common/Android] add version info

### PR DESCRIPTION
**Pull request by jaeyun-jung**
1. add new function to get the NNStreamer version string.
2. get nnstreamer version string in Android method.
3. print log about version info when initializing the nnstreamer.

Signed-off-by: Jaeyun Jung <jy1210.jung@samsung.com>

### CODE REVIEW

**Comment by myungjoo** [comment]
Why do we want to have version info in .ini file?

**Comment by jaeyun-jung** [comment]
@myungjoo  To get the debug info in target device later

**Comment by myungjoo** [comment]
> @myungjoo To get the debug info in target device later

If you want version info of nnstreamer-library/plugin, add internal API (e.g., at /gst/nnstreamer/nnstreamer.c)

If this is for debugging/devel only, not for actual behavior, let's create another "category":
```
# Values in debug section does not affect the behavior. It's for debugging/development only.
[debug]
version=...
```

**Comment by jaeyun-jung** [comment]
PR updated
2020-01-21 add function to get the version string of nnstreamer

**Pull request merged**
