### PR TITLE
[Tests] testAll.sh: Added a function to display a usage

### PR DESCRIPTION
**Pull request by leemgs**
This commit is to append a display usage function in testAll.sh
Note that append the usage whenever you append the new functions
in testAll.sh file.

* After this PR:
```bash
$ ./testAll.sh --help
Usage: ./testAll.sh [option...]

   1,                 Generate GStreamer Pipeline Graphs
                      with GST_DEBUG_DUMP_DOT_DIR
```

Signed-off-by: Geunsik Lim <geunsik.lim@samsung.com>

---
# [Template] PR Description

In general, github system automatically copies your commit message for your convenience.
Please remove unused part of the template after writing your own PR description with this template.
```bash
$ git commit -s filename1 filename2 ... [enter]

Summarize changes in around 50 characters or less

More detailed explanatory text, if necessary. Wrap it to about 72
characters or so. In some contexts, the first line is treated as the
subject of the commit and the rest of the text as the body. The
blank line separating the summary from the body is critical;
various tools like `log`, `shortlog` and `rebase` can get confused 
if you run the two together.

Further paragraphs come after blank lines.

**Changes proposed in this PR:**
- Bullet points are okay, too
- Typically a hyphen or asterisk is used for the bullet, preceded
  by a single space, with blank lines in between, but conventions vary here.

Resolves: #123
See also: #456, #789

**Self evaluation:**
1. Build test: [ ]Passed [ ]Failed [*]Skipped
2. Run test: [ ]Passed [ ]Failed [* ]Skipped

**How to evaluate:**
1. Describe how to evaluate in order to be reproduced by reviewer(s).

Add signed-off message automatically by running **$git commit -s ...** command.

$ git push origin <your_branch_name>
```

### CODE REVIEW

**Comment by leemgs** [comment]
> The first option, "$1" is the path to gst plugins in the current code. 
> Resolve argument parsing first if you want to add "-p" option

Thanks. Updated.

**Comment by myungjoo** [comment]
Please await for SSAT. The current testAll.sh / testAPI.sh are to be removed soon. (Just one bug to go)

**Comment by myungjoo** [comment]
Note that ```ssat -h``` will do what you want :)

**Comment by myungjoo** [comment]
testAll.sh is no more existing and ssat -h will do what you want..

**Pull request closed without merging**
