### PR TITLE
[Filter] create new structure for multi tensors

### PR DESCRIPTION
**Pull request by helloahn**
Define the new structure as a standard unit of data tensor. 
It will be allocated and used to store the tensor data.

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped

Signed-off-by: HyoungjooAhn <hello.ahn@samsung.com>

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
It is better to use size_t

uint8_t size; -> size_t size;

**Comment by helloahn** [comment]
@jaeyun-jung it's applied :)

**Comment by helloahn** [comment]
@myungjoo Actually it will be used for the data-flow of tensor between `tensor_filter` - `tflite`. Since current architecture we cannot make multi tensor available, we needed the new structure. the validity checking was done and it shared at #536 :)

**Comment by helloahn** [comment]
Furthermore this new definition will be applied as the key of multi tensor from next PR :)

**Comment by myungjoo** [comment]
Please rebase

**Comment by helloahn** [comment]
it's done

**Comment by jaeyun-jung** [comment]
Please remove the structure 'tensors_meta'. We does not use this structure now.

**Comment by helloahn** [comment]
it's done

**Pull request merged**
