### PR TITLE
[Filter] change the policy of model files download

### PR DESCRIPTION
**Pull request by helloahn**
add a flag 'DISABLE_MODEL_DOWNLOAD' and block it at gbs build. It will be improved as rpm packaging for the model files rather than download them.

**Self evaluation:**
1. Build test: [*]Passed [ ]Failed [ ]Skipped
2. Run test: [*]Passed [ ]Failed [ ]Skipped

Signed-off-by: HyoungjooAhn <hello.ahnn@gmail.com>

### CODE REVIEW

**Comment by jaeyun-jung** [comment]
how about change feature name, ENABLE_MODEL_DOWNLOAD

**Comment by jaeyun-jung** [comment]
Also, about tf and tf-lite, please consider to change feature name, ENABLE_--.

**Comment by helloahn** [comment]
@myungjoo 
How do you think of the upper suggestion?
If you agree, I'll change the flags which started with `DISABLE_` to `ENABLE` and the related logic.

**Comment by myungjoo** [comment]
Changing all options to "ENABLE" from "DISABLE" is more intuitive. So, if you feel like to do it, please go ahead.

**Comment by helloahn** [comment]
@jaeyun-jung please check the update :)

**Pull request merged**
